const colors = require("tailwindcss/colors");
const lineClamp = require("@tailwindcss/line-clamp");

module.exports = {
  important: true,
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      yellow: colors.yellow,
      transparent: colors.transparent,
      primary1: "#C9F3FB",
      primary2: "#93E2F7",
      primary3: "#016DB2",
      primary4: "#005499",
      primary5: "#003F80",
      primary6: "#4EAEEC",
      secondary1: "#1192E8",
      secondaryCyan: "#37B6E2",
      accent3: "#3267E3",
      accent1: "#F0F3FF",
      bg1: "#F2F4F6",
      bg2: "#F2F4F8",
      bg3: "#F6F6F6",
      bg4: "#FBFBFB",
      green: "#4BB543",
      green1: "#4BB543",
      success1: "#F4FBF4",
      success2: "#B8E3B5",
      success3: "#4BB543",
      warning1: "#FEF9F1",
      warning2: "#F9D79F",
      warning3: "#F5BB5C",
      danger1: "#FFF4F2",
      danger2: "#EEB4B0",
      danger3: "#CB3A31",
      grey: "#C1C7CD",
      grey2: "#C4C4C4",
      lightGrey: "#DDE1E6",
      darkGrey: "#878D96",
      gray: colors.gray,
      text1: "#444444",
      white: colors.white,
      red: colors.red,
      red1: "#CB0000",
      red2: "#CB3A31",
      teal: colors.teal,
      black: colors.black,
      coffee: "#444444",
      baseGrey: "#325366",
      baseGradient: "#6CC7FE",
      topGradient: "#111111",
      iconGradient: "#FEFEFE",
      info1: "#F0F3FF",
      info2: "#B1C5F6",
      info3: "#3267E3",
      info4: "#193AA3",
    },
    extend: {
      boxShadow: {
        primary: "0px 10px 20px rgba(0, 0, 0, 0.05)",
      },
    },
    fontFamily: {
      primary: ["Inter", "ui-serif", "Georgia"],
      secondary: ["Inter", "Roboto", "system-ui"],
      tertiary: ["IBM Plex Sans", "Roboto", "system-ui"],
    },
  },
  plugins: [lineClamp],
};
